In [1]:
import tensorflow as tf
tf.enable_eager_execution()
config = tf.ConfigProto()
config.gpu_options.allow_growth = True 
config.gpu_options.per_process_gpu_memory_fraction = 0.4

In [2]:
import numpy as np

ndarray = np.ones([3, 3])

tensor = tf.multiply(ndarray, 42)
print("The .numpy() method explicitly converts a Tensor to a numpy array")
print(tensor.numpy())

The .numpy() method explicitly converts a Tensor to a numpy array
[[42. 42. 42.]
 [42. 42. 42.]
 [42. 42. 42.]]


In [3]:
x = tf.random_uniform([3, 3])

print("Is there a GPU available: "),
print(tf.test.is_gpu_available())

print("Is the Tensor on GPU #0:  "),
print(x.device.endswith('GPU:0'))

Is there a GPU available: 
True
Is the Tensor on GPU #0:  
True


In [6]:
x.device

'/job:localhost/replica:0/task:0/device:GPU:0'

## Dataset

In [7]:
ds_tensors = tf.data.Dataset.from_tensor_slices([1, 2, 3, 4, 5, 6])

# Create a CSV file
import tempfile
_, filename = tempfile.mkstemp()

with open(filename, 'w') as f:
  f.write("""Line 1
Line 2
Line 3
  """)

ds_file = tf.data.TextLineDataset(filename)

In [12]:
filename
# https://docs.python.org/2/library/tempfile.html 
# tempfile create temporary files

'/tmp/tmpnlemscnd'

In [8]:
ds_tensors = ds_tensors.map(tf.square).shuffle(2).batch(2)

ds_file = ds_file.batch(2)

In [10]:
print('Elements of ds_tensors:')
for x in ds_tensors:
  print(x)

print('\nElements in ds_file:')
for x in ds_file:
  print(x)

Elements of ds_tensors:
tf.Tensor(
[[  16   81]
 [   1 1296]], shape=(2, 2), dtype=int32)
tf.Tensor([[256 625]], shape=(1, 2), dtype=int32)

Elements in ds_file:
tf.Tensor(
[[b'Line 1' b'Line 2']
 [b'Line 3' b'  ']], shape=(2, 2), dtype=string)


## Question
are these features not available if eager execution is not activated?
tensorflow guide https://www.tensorflow.org/guide/datasets seems to tell a different story than tensorflow tutorial

is this a new version tensorflow that includes pytorch like features?